### ISSUE TITLE
Process hanging at 'Tagging and parsing...'

### ISSUE THREAD

**Issue by C-Holzer** [dbamman/book-nlp#4]
I am processing 400+ white papers to develop an ontology as part of my research. The documents are all in plain text but the processing of a few documents hangs while 'Tagging and parsing...' shows on the screen. Is there a way to determine what the error is?

**Comment by NikhilPr95** [comment]
Yes, I'm not the author of this code, but I am using it and I have had this problem before. Go through BookNLP.Java and put print statement everywhere. It is most likely an infinite loop somewhere. I had this problem when the sentences I was parsing had parse trees which had loops in them. This may or may not be your problem, but going through the executed java program and putting print statements at the important places is the way to go. There's a good chance the error will be in SyntaxAnnotator.Java or PhraseAnnotator.java

**Comment by C-Holzer** [comment]
Thank you for the advise. I will implement it and see what it shows me.
